/*
 * JSP generated by Resin-4.0.47 (built Thu, 03 Dec 2015 10:34:34 PST)
 */

package _jsp._user;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import com.beanwiz.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import javax.servlet.*;
import javax.servlet.http.*;
import javax.naming.*;
import javax.sql.*;
import com.webapp.utils.*;

public class _tablelist__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, "/errorpage.jsp", session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    java.util.TreeMap OverrideMap;
    synchronized (pageContext.getSession()) {
      OverrideMap = (java.util.TreeMap) pageContext.getSession().getAttribute("OverrideMap");
      if (OverrideMap == null) {
        OverrideMap = new java.util.TreeMap();
        pageContext.getSession().setAttribute("OverrideMap", OverrideMap);
      }
    }
    out.write(_jsp_string1, 0, _jsp_string1.length);
    java.util.TreeMap FieldMap;
    synchronized (pageContext.getSession()) {
      FieldMap = (java.util.TreeMap) pageContext.getSession().getAttribute("FieldMap");
      if (FieldMap == null) {
        FieldMap = new java.util.TreeMap();
        pageContext.getSession().setAttribute("FieldMap", FieldMap);
      }
    }
    out.write(_jsp_string1, 0, _jsp_string1.length);
    java.util.Vector ManField;
    synchronized (pageContext.getSession()) {
      ManField = (java.util.Vector) pageContext.getSession().getAttribute("ManField");
      if (ManField == null) {
        ManField = new java.util.Vector();
        pageContext.getSession().setAttribute("ManField", ManField);
      }
    }
    out.write(_jsp_string2, 0, _jsp_string2.length);
     
String appPath = request.getContextPath() ;
String thisFile = appPath+request.getServletPath() ;

com.beanwiz.LoggedUser LogUsr  = (com.beanwiz.LoggedUser)session.getAttribute("theWizardUser");
if(LogUsr == null ) LogUsr =  LoginHelper.autoLoginCheck(application,session,request );

String WebAppName = request.getParameter("WebAppName");
String JNDIDSN = request.getParameter("JNDIDSN");
 

String Database=null; 
String DriverName=null;
String[] exld = null ;


    out.write(_jsp_string3, 0, _jsp_string3.length);
    pageContext.include("/assets/include-page/common/meta-tag.jsp", true);out.write(_jsp_string4, 0, _jsp_string4.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string5, 0, _jsp_string5.length);
    pageContext.include("/assets/include-page/css/main-css.jsp", true);out.write(_jsp_string6, 0, _jsp_string6.length);
    pageContext.include("/assets/include-page/common/main-head-js.jsp", true);out.write(_jsp_string7, 0, _jsp_string7.length);
    pageContext.include("/user/assets-user/include-page/header-user.jsp", true);out.write(_jsp_string8, 0, _jsp_string8.length);
     
Context env = (Context) new InitialContext().lookup("java:comp/env");
DataSource source = (DataSource) env.lookup(JNDIDSN);
Connection conn = source.getConnection();
com.webapp.utils.PortableSQL psql = new com.webapp.utils.PortableSQL(conn) ;
try
{

DatabaseMetaData md=conn.getMetaData();
Database=conn.getCatalog();
DriverName=md.getDriverName(); 

switch(psql.getEngine())
{
  case PortableSQL.ORACLE:
  exld =  new String[]  { "DR$", 	"WWV_" , "BIN$", "OGIS_" , "SDO_", "AUDIT_ACTIONS", "ODCI_",	"OL$" , 
	"XDB$", "DUAL", "IMPDP_STATS", "KU$NOEXP_TAB", "PLAN_TABLE$", "PSTUBTBL",  "STMT_AUDIT_OPTION_MAP", 
	"SYSTEM_PRIVILEGE_MAP", "TABLE_PRIVILEGE_MAP", "WRI$_ADV_ASA_RECO_DATA" , "DEF$_TEMP$LOB", "HELP"  } ;
	
  break ;
}

    out.write(_jsp_string9, 0, _jsp_string9.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string10, 0, _jsp_string10.length);
    out.print((appPath ));
    out.write(_jsp_string11, 0, _jsp_string11.length);
    out.print((Database ));
    out.write(_jsp_string12, 0, _jsp_string12.length);
    out.print((psql.getEngineName() ));
    out.write(_jsp_string13, 0, _jsp_string13.length);
    out.print((DriverName ));
    out.write(_jsp_string14, 0, _jsp_string14.length);
     
// See if database struct definition is available ( driver specific )
if(DriverName.equalsIgnoreCase("MySQL-AB JDBC Driver") || DriverName.equalsIgnoreCase("MySQL Connector Java"))
{
 // MySQL is supported.

    out.write(_jsp_string15, 0, _jsp_string15.length);
    out.print((appPath ));
    out.write(_jsp_string16, 0, _jsp_string16.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string17, 0, _jsp_string17.length);
    
}

    out.write(_jsp_string18, 0, _jsp_string18.length);
    out.print((appPath ));
    out.write(_jsp_string16, 0, _jsp_string16.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string19, 0, _jsp_string19.length);
    out.print((appPath ));
    out.write(_jsp_string20, 0, _jsp_string20.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string21, 0, _jsp_string21.length);
    out.print((PortableSQL.MYSQL ));
    out.write(_jsp_string22, 0, _jsp_string22.length);
    out.print((appPath ));
    out.write(_jsp_string23, 0, _jsp_string23.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string21, 0, _jsp_string21.length);
    out.print((PortableSQL.MYSQL ));
    out.write(_jsp_string24, 0, _jsp_string24.length);
    out.print((appPath ));
    out.write(_jsp_string20, 0, _jsp_string20.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string21, 0, _jsp_string21.length);
    out.print((PortableSQL.POSTGRE ));
    out.write(_jsp_string25, 0, _jsp_string25.length);
    out.print((appPath ));
    out.write(_jsp_string23, 0, _jsp_string23.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string21, 0, _jsp_string21.length);
    out.print((PortableSQL.POSTGRE ));
    out.write(_jsp_string26, 0, _jsp_string26.length);
    out.print((appPath ));
    out.write(_jsp_string20, 0, _jsp_string20.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string21, 0, _jsp_string21.length);
    out.print((PortableSQL.DB2 ));
    out.write(_jsp_string22, 0, _jsp_string22.length);
    out.print((appPath ));
    out.write(_jsp_string23, 0, _jsp_string23.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string21, 0, _jsp_string21.length);
    out.print((PortableSQL.DB2 ));
    out.write(_jsp_string27, 0, _jsp_string27.length);
    out.print((appPath ));
    out.write(_jsp_string20, 0, _jsp_string20.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string21, 0, _jsp_string21.length);
    out.print((PortableSQL.MSSQL ));
    out.write(_jsp_string25, 0, _jsp_string25.length);
    out.print((appPath ));
    out.write(_jsp_string23, 0, _jsp_string23.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string21, 0, _jsp_string21.length);
    out.print((PortableSQL.MSSQL ));
    out.write(_jsp_string28, 0, _jsp_string28.length);
    out.print((appPath ));
    out.write(_jsp_string20, 0, _jsp_string20.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string21, 0, _jsp_string21.length);
    out.print((PortableSQL.ORACLE ));
    out.write(_jsp_string22, 0, _jsp_string22.length);
    out.print((appPath ));
    out.write(_jsp_string23, 0, _jsp_string23.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string21, 0, _jsp_string21.length);
    out.print((PortableSQL.ORACLE ));
    out.write(_jsp_string29, 0, _jsp_string29.length);
    out.print((appPath ));
    out.write(_jsp_string20, 0, _jsp_string20.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string21, 0, _jsp_string21.length);
    out.print((PortableSQL.H2 ));
    out.write(_jsp_string22, 0, _jsp_string22.length);
    out.print((appPath ));
    out.write(_jsp_string23, 0, _jsp_string23.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string21, 0, _jsp_string21.length);
    out.print((PortableSQL.H2 ));
    out.write(_jsp_string30, 0, _jsp_string30.length);
    out.print((appPath ));
    out.write(_jsp_string20, 0, _jsp_string20.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string21, 0, _jsp_string21.length);
    out.print((PortableSQL.SQLITE ));
    out.write(_jsp_string31, 0, _jsp_string31.length);
    out.print((appPath ));
    out.write(_jsp_string23, 0, _jsp_string23.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string21, 0, _jsp_string21.length);
    out.print((PortableSQL.SQLITE ));
    out.write(_jsp_string32, 0, _jsp_string32.length);
    out.print((Database ));
    out.write(_jsp_string33, 0, _jsp_string33.length);
    out.print((WebAppName ));
    out.write(_jsp_string34, 0, _jsp_string34.length);
      
ArrayList<String> AlphaList = new ArrayList<String>();

String[] tbl_types = {"TABLE"} ;
java.sql.ResultSet rsltList = md.getTables(null,null,null,tbl_types );
int no=0;
StringBuilder sbAn = new StringBuilder("Go To : ");
String OldChar = "";
while(rsltList.next())
{ 
		String TableName = rsltList.getString("TABLE_NAME");	
		// Check in exlusion list
		boolean bNotThere = true ;
  
			if(exld != null)
			{
		           for(int i=0 ; i< exld.length ; i++) 
			         {
			            if( TableName.startsWith(exld[i]) ) bNotThere = false ;
			         }
		  }
		
		
	     if(bNotThere)
		   {	
			   no++;
			 	
				boolean bLink = false;
				String Chk = TableName.substring(0,1).toUpperCase();
			  if(!OldChar.equalsIgnoreCase(Chk))	
				{
				  sbAn.append("&nbsp;<a href=\"#"+Chk+"\"><big>"+Chk+"</big></a>&nbsp;");
					bLink=true;
				 
				
    out.write(_jsp_string35, 0, _jsp_string35.length);
    out.print((Chk ));
    out.write(_jsp_string36, 0, _jsp_string36.length);
     
				} 
				OldChar=Chk;
				
    out.write(_jsp_string37, 0, _jsp_string37.length);
    out.print((TableName ));
    out.write(_jsp_string38, 0, _jsp_string38.length);
    out.print((no ));
    out.write(_jsp_string39, 0, _jsp_string39.length);
    out.print((TableName ));
    out.write(_jsp_string40, 0, _jsp_string40.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string41, 0, _jsp_string41.length);
    out.print((WebAppName ));
    out.write(_jsp_string42, 0, _jsp_string42.length);
    out.print((TableName ));
    out.write(_jsp_string43, 0, _jsp_string43.length);
    out.print((DriverName ));
    out.write(_jsp_string44, 0, _jsp_string44.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string41, 0, _jsp_string41.length);
    out.print((WebAppName ));
    out.write(_jsp_string42, 0, _jsp_string42.length);
    out.print((TableName ));
    out.write(_jsp_string43, 0, _jsp_string43.length);
    out.print((DriverName ));
    out.write(_jsp_string45, 0, _jsp_string45.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string41, 0, _jsp_string41.length);
    out.print((WebAppName ));
    out.write(_jsp_string42, 0, _jsp_string42.length);
    out.print((TableName ));
    out.write(_jsp_string43, 0, _jsp_string43.length);
    out.print((DriverName ));
    out.write(_jsp_string46, 0, _jsp_string46.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string42, 0, _jsp_string42.length);
    out.print((TableName ));
    out.write(_jsp_string47, 0, _jsp_string47.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string42, 0, _jsp_string42.length);
    out.print((TableName ));
    out.write(_jsp_string48, 0, _jsp_string48.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string42, 0, _jsp_string42.length);
    out.print((TableName ));
    out.write(_jsp_string49, 0, _jsp_string49.length);
    out.print((appPath ));
    out.write(_jsp_string50, 0, _jsp_string50.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string42, 0, _jsp_string42.length);
    out.print((TableName ));
    out.write(_jsp_string51, 0, _jsp_string51.length);
    out.print((DriverName ));
    out.write(_jsp_string52, 0, _jsp_string52.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string42, 0, _jsp_string42.length);
    out.print((TableName ));
    out.write(_jsp_string53, 0, _jsp_string53.length);
    out.print((DriverName ));
    out.write(_jsp_string52, 0, _jsp_string52.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string42, 0, _jsp_string42.length);
    out.print((TableName ));
    out.write(_jsp_string54, 0, _jsp_string54.length);
    out.print((DriverName ));
    out.write(_jsp_string52, 0, _jsp_string52.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string42, 0, _jsp_string42.length);
    out.print((TableName ));
    out.write(_jsp_string55, 0, _jsp_string55.length);
      
       } // end if (bNotThere)
    } // end while while(rsltList.next())
rsltList.close();		

    out.write(_jsp_string56, 0, _jsp_string56.length);
    pageContext.include("/assets/include-page/js/main-js.jsp", true);out.write(_jsp_string57, 0, _jsp_string57.length);
    out.print((sbAn.toString() ));
    out.write(_jsp_string58, 0, _jsp_string58.length);
    
}
finally
{
conn.close();
FieldMap.clear();
ManField.clear();
OverrideMap.clear();
}
    out.write(_jsp_string2, 0, _jsp_string2.length);
     
if(exld != null)
{ 

    out.write(_jsp_string59, 0, _jsp_string59.length);
     for(int i=0 ; i< exld.length ; i++) out.print( exld[i]+( (i< exld.length-1)? ", " : " ") ) ; 
    out.write(_jsp_string60, 0, _jsp_string60.length);
     
} 

    out.write(_jsp_string61, 0, _jsp_string61.length);
    pageContext.include("/assets/include-page/common/footer.jsp", true);out.write(_jsp_string1, 0, _jsp_string1.length);
    pageContext.include("/assets/include-page/common/Google-Analytics.jsp", true);out.write(_jsp_string62, 0, _jsp_string62.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 8324212715306645294L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("user/tablelist.jsp"), -4114971742409682771L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string61;
  private final static char []_jsp_string32;
  private final static char []_jsp_string44;
  private final static char []_jsp_string22;
  private final static char []_jsp_string13;
  private final static char []_jsp_string58;
  private final static char []_jsp_string3;
  private final static char []_jsp_string49;
  private final static char []_jsp_string23;
  private final static char []_jsp_string12;
  private final static char []_jsp_string57;
  private final static char []_jsp_string62;
  private final static char []_jsp_string40;
  private final static char []_jsp_string29;
  private final static char []_jsp_string18;
  private final static char []_jsp_string4;
  private final static char []_jsp_string55;
  private final static char []_jsp_string59;
  private final static char []_jsp_string26;
  private final static char []_jsp_string42;
  private final static char []_jsp_string54;
  private final static char []_jsp_string6;
  private final static char []_jsp_string39;
  private final static char []_jsp_string41;
  private final static char []_jsp_string47;
  private final static char []_jsp_string48;
  private final static char []_jsp_string52;
  private final static char []_jsp_string56;
  private final static char []_jsp_string45;
  private final static char []_jsp_string51;
  private final static char []_jsp_string36;
  private final static char []_jsp_string19;
  private final static char []_jsp_string37;
  private final static char []_jsp_string28;
  private final static char []_jsp_string10;
  private final static char []_jsp_string34;
  private final static char []_jsp_string21;
  private final static char []_jsp_string15;
  private final static char []_jsp_string14;
  private final static char []_jsp_string5;
  private final static char []_jsp_string50;
  private final static char []_jsp_string35;
  private final static char []_jsp_string9;
  private final static char []_jsp_string53;
  private final static char []_jsp_string1;
  private final static char []_jsp_string8;
  private final static char []_jsp_string20;
  private final static char []_jsp_string11;
  private final static char []_jsp_string16;
  private final static char []_jsp_string43;
  private final static char []_jsp_string38;
  private final static char []_jsp_string30;
  private final static char []_jsp_string24;
  private final static char []_jsp_string31;
  private final static char []_jsp_string27;
  private final static char []_jsp_string7;
  private final static char []_jsp_string33;
  private final static char []_jsp_string46;
  private final static char []_jsp_string0;
  private final static char []_jsp_string17;
  private final static char []_jsp_string2;
  private final static char []_jsp_string25;
  private final static char []_jsp_string60;
  static {
    _jsp_string61 = "\r\n	\r\n</div> <!-- /container -->\r\n".toCharArray();
    _jsp_string32 = "\">Indexes</a></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n\r\n</div>		\r\n</div> 					\r\n					</div>\r\n					</div>\r\n\r\n        </div>\r\n      </div>			\r\n	</div>\r\n</div>\r\n\r\n	\r\n\r\n<div class=\"panel  panel-primary\">\r\n  <!-- Default panel contents -->\r\n  <div class=\"panel-heading\"><big><i class=\"fa fa-table fa-lg\"></i>&nbsp;&nbsp;Table List : ".toCharArray();
    _jsp_string44 = "\">Bean</a></td>\r\n<td><a href=\"jsppagewiz.jsp?JNDIDSN=".toCharArray();
    _jsp_string22 = "\" target=\"_blank\" >Tables</a></td>\r\n		<td><a href=\"".toCharArray();
    _jsp_string13 = "</strong></span>\r\n					</h4>\r\n					<span class=\"pull-right p1\"><i class=\"glyphicon glyphicon-minus\"></i></span>\r\n        </div>\r\n        <div class=\"panel-body\">\r\n				\r\n					<div class=\"row\">\r\n					<div class=\"col-md-6\">\r\n<div class=\"panel panel-primary\">\r\n  <!-- Default panel contents -->\r\n  <div class=\"panel-heading\">\r\n	<h3 class=\"panel-title\"><i class=\"fa fa-cogs fa-lg\"></i>&nbsp;&nbsp;Info</h3>\r\n	</div>\r\n\r\n\r\n  <!-- List group -->\r\n  <ul class=\"list-group\">\r\n    <li class=\"list-group-item\"><strong>Driver : </strong><span class=\"text-muted\">".toCharArray();
    _jsp_string58 = "');\r\n\r\n$(document).on('click', '.panel div.clickablePanel', function (e) {\r\n    var $this = $(this);\r\n    if (!$this.hasClass('panel-collapsed')) {\r\n        $this.parents('.panel').find('.panel-body').slideUp();\r\n        $this.addClass('panel-collapsed');\r\n        $this.find('.p1 i').removeClass('glyphicon-minus').addClass('glyphicon-plus');\r\n    } else {\r\n        $this.parents('.panel').find('.panel-body').slideDown();\r\n        $this.removeClass('panel-collapsed');\r\n        $this.find('.p1 i').removeClass('glyphicon-plus').addClass('glyphicon-minus');\r\n    }\r\n});\r\n$(document).ready(function () {\r\n    $('.panel div.clickablePanel').click();\r\n});\r\n\r\n</script>\r\n".toCharArray();
    _jsp_string3 = "\r\n<!DOCTYPE HTML>\r\n<!--[if lt IE 7]>      <html class=\"no-js lt-ie9 lt-ie8 lt-ie7\" lang=\"en\"> <![endif]-->\r\n<!--[if IE 7]>         <html class=\"no-js lt-ie9 lt-ie8\" lang=\"en\"> <![endif]-->\r\n<!--[if IE 8]>         <html class=\"no-js lt-ie9\" lang=\"en\"> <![endif]-->\r\n<!--[if gt IE 8]><!--> <html class=\"no-js\" lang=\"en\"> <!--<![endif]-->\r\n<head>\r\n".toCharArray();
    _jsp_string49 = "\" target=\"_blank\"><samp><i class=\"fa fa-hand-o-right fa-lg\"></i>&nbsp;Field List</samp></a></li>\r\n    <li><a href=\"".toCharArray();
    _jsp_string23 = "/user/createdatabasescripts/createindexscript.jsp?JNDIDSN=".toCharArray();
    _jsp_string12 = "</strong></li>\r\n            </ol>\r\n	    </div>\r\n    </div>\r\n<hr class=\"pageheaderHR\" />\r\n			\r\n<div class=\"row\">\r\n  <div class=\"col-md-12\">\r\n\r\n      <div class=\"panel panel-default\">\r\n        <div class=\"panel-heading clickablePanel\">\r\n          <h4 class=\"panel-title\">\r\n					<i class=\"fa fa-database text-primary\"></i>&nbsp;&nbsp;Detected DB Engine : <strong>".toCharArray();
    _jsp_string57 = "\r\n\r\n<script type=\"text/javascript\">\r\n\r\n$('#ANCH').html('".toCharArray();
    _jsp_string62 = "\r\n</body>\r\n</html>\r\n".toCharArray();
    _jsp_string40 = "</td>\r\n<td><a href=\"newbeanwiz.jsp?JNDIDSN=".toCharArray();
    _jsp_string29 = "\" target=\"_blank\" >Indexes</a></td>\r\n</tr>\r\n<tr>\r\n    <td>H2 Database</td>\r\n		<td><a href=\"".toCharArray();
    _jsp_string18 = "\r\n-->\r\n\r\n\r\n  </ul>\r\n</div>		\r\n\r\n<div class=\"panel panel-primary\">\r\n  <!-- Default panel contents -->\r\n  <div class=\"panel-heading\">\r\n	<h3 class=\"panel-title\"><i class=\"fa fa-cogs fa-lg\"></i>&nbsp;&nbsp;SQL Script : MySQL</h3>\r\n	</div>\r\n  <!-- List group -->\r\n  <ul class=\"list-group\">\r\n    <li class=\"list-group-item\"><a href=\"".toCharArray();
    _jsp_string4 = "	\r\n<title>Tables in ".toCharArray();
    _jsp_string55 = "\" target=\"_blank\"><samp><i class=\"fa fa-hand-o-right fa-lg\"></i>&nbsp;Excel Export</samp></a></li>\r\n  </ul>\r\n</td>\r\n</tr>\r\n".toCharArray();
    _jsp_string59 = "\r\n<br />\r\n<br />\r\n\r\n<b>Excluded Tables</b> ( System tables ):&nbsp;&nbsp; ".toCharArray();
    _jsp_string26 = "\" target=\"_blank\">Indexes</a></td>\r\n</tr>\r\n<tr>\r\n    <td>IBM DB2</td>\r\n		<td><a href=\"".toCharArray();
    _jsp_string42 = "&TableName=".toCharArray();
    _jsp_string54 = "\" target=\"_blank\"><samp><i class=\"fa fa-hand-o-right fa-lg\"></i>&nbsp;Table Data Dump</samp></a></li>\r\n    <li><a href=\"excelexport/query.jsp?DriverName=".toCharArray();
    _jsp_string6 = "		\r\n".toCharArray();
    _jsp_string39 = "</td>\r\n<td width=\"23%\">".toCharArray();
    _jsp_string41 = "&WebAppName=".toCharArray();
    _jsp_string47 = "\" target=\"_blank\"><samp><i class=\"fa fa-hand-o-right fa-lg\"></i>&nbsp;Request Parameter</samp></a></li>\r\n    <li><a href=\"forms/tableform.jsp?JNDIDSN=".toCharArray();
    _jsp_string48 = "\" target=\"_blank\"><samp><i class=\"fa fa-hand-o-right fa-lg\"></i>&nbsp;Form Field</samp></a></li>\r\n    <li><a href=\"tablefields.jsp?JNDIDSN=".toCharArray();
    _jsp_string52 = "&JNDIDSN=".toCharArray();
    _jsp_string56 = "\r\n</tbody>\r\n</table>\r\n\r\n</div>	\r\n</div>\r\n</div>\r\n".toCharArray();
    _jsp_string45 = "\">JSP</a></td>\r\n<td><a href=\"jsploginwiz.jsp?JNDIDSN=".toCharArray();
    _jsp_string51 = "\" target=\"_blank\"><samp><i class=\"fa fa-hand-o-right fa-lg\"></i>&nbsp;old for mysql</samp></a></li>\r\n    <li><a href=\"createtablescript/index.jsp?DriverName=".toCharArray();
    _jsp_string36 = "\" ></a>\r\n\r\n<table class=\"table table-striped table-bordered\" >\r\n<thead>\r\n<tr>\r\n<th width=\"5%\">#</th>\r\n<th width=\"23%\">Database Tables</th>\r\n<th colspan=\"4\">Code Generation Tools</th>\r\n</tr>\r\n</thead>\r\n<tbody>\r\n				".toCharArray();
    _jsp_string19 = "\" target=\"_blank\">Create Database Structure</a></li>\r\n  </ul>\r\n</div>					\r\n			\r\n					</div>\r\n					<div class=\"col-md-6\">\r\n<div class=\"panel panel-primary\">\r\n  <!-- Default panel contents -->\r\n  <div class=\"panel-heading\">\r\n	<h3 class=\"panel-title\"><i class=\"fa fa-cogs fa-lg\"></i>&nbsp;&nbsp;Database Creation Script</h3>\r\n	</div>\r\n  <div class=\"panel-body\">\r\n    <p>Generate SQL Script for creating tables for various database engines</p>\r\n  </div>\r\n\r\n<!-- Table -->\r\n<div class=\"table-responsive\">\r\n<table class=\"table table-striped table-bordered\">\r\n<thead>\r\n<tr>\r\n<th>Database Engine</th>\r\n<th>Table SQL</th>\r\n<th>Indexes</th>\r\n</tr>\r\n</thead>\r\n<tbody>	\r\n<tr>\r\n    <td>MySQL</td>\r\n		<td><a href=\"".toCharArray();
    _jsp_string37 = "\r\n<tr id=\"".toCharArray();
    _jsp_string28 = "\" target=\"_blank\">Indexes</a></td>\r\n</tr>\r\n<tr>\r\n    <td>Oracle</td>\r\n		<td><a href=\"".toCharArray();
    _jsp_string10 = "</span></span></h4>	\r\n	    </div>\r\n			<div class=\"col-md-6 col-xs-12\">\r\n            <ol class=\"breadcrumb text-right\">\r\n               <li><a href=\"".toCharArray();
    _jsp_string34 = "</big></div>\r\n  <div class=\"panel-body\">\r\n    <div class=\"well well-sm text-center row-fluid-text\" id=\"ANCH\" style=\"margin-bottom: 0px;\"></div>	\r\n  \r\n\r\n\r\n<div class=\"table-responsive\">	\r\n<table class=\"table table-striped table-bordered\">\r\n".toCharArray();
    _jsp_string21 = "&SQLEngine=".toCharArray();
    _jsp_string15 = "\r\n<li class=\"list-group-item\"><a href=\"".toCharArray();
    _jsp_string14 = "</span></li>\r\n<!-- 		  			\r\n".toCharArray();
    _jsp_string5 = "</title>\r\n".toCharArray();
    _jsp_string50 = "/user/tabledef/showcreatetable.jsp?JNDIDSN=".toCharArray();
    _jsp_string35 = "\r\n				</table>\r\n<a id=\"".toCharArray();
    _jsp_string9 = "\r\n\r\n    <div class=\"row page-header11\">\r\n    	<div class=\"col-md-6 col-xs-12\">\r\n        <h4 class=\"page-title11\"><i class=\"fa fa-send-o\"></i>&nbsp;&nbsp;<span class=\"text-info\">JNDI: <span class=\"text-muted\">".toCharArray();
    _jsp_string53 = "\" target=\"_blank\"><samp><i class=\"fa fa-hand-o-right fa-lg\"></i>&nbsp;Table Script</samp></a></li>\r\n    <li><a href=\"tabledump/index.jsp?DriverName=".toCharArray();
    _jsp_string1 = "\r\n".toCharArray();
    _jsp_string8 = "	\r\n\r\n<div class=\"container-fluid\">\r\n".toCharArray();
    _jsp_string20 = "/user/createdatabasescripts/createsqlscript.jsp?JNDIDSN=".toCharArray();
    _jsp_string11 = "/user/index.jsp\"><i class=\"fa fa-home fa-lg\"></i></a></li>\r\n               <li class=\"active\">Table List : <strong>".toCharArray();
    _jsp_string16 = "/user/dbstruct/mysql-db-struct.jsp?JNDIDSN=".toCharArray();
    _jsp_string43 = "&DriverName=".toCharArray();
    _jsp_string38 = "\" >\r\n<td width=\"5%\">".toCharArray();
    _jsp_string30 = "\" target=\"_blank\" >Indexes</a></td>\r\n</tr>\r\n<tr>\r\n    <td>SQLite</td>\r\n		<td><a href=\"".toCharArray();
    _jsp_string24 = "\" target=\"_blank\" >Indexes</a></td>\r\n</tr>\r\n<tr>\r\n    <td>Postgre SQL</td>\r\n		<td><a href=\"".toCharArray();
    _jsp_string31 = "\">Tables</a></td>\r\n		<td><a href=\"".toCharArray();
    _jsp_string27 = "\" target=\"_blank\" >Indexes</a></td>\r\n</tr>\r\n<tr>\r\n    <td>MS SQL</td>\r\n		<td><a href=\"".toCharArray();
    _jsp_string7 = "\r\n\r\n<style type=\"text/css\">\r\n.clickablePanel{cursor: pointer;}\r\n.clickablePanel .glyphicon{background: rgba(0, 0, 0, 0.15);display: inline-block;padding: 6px 12px;border-radius: 4px}\r\n.clickablePanel  span{margin-top: -23px;font-size: 15px;margin-right: -9px;}\r\n</style>\r\n\r\n</head>\r\n<body>   \r\n".toCharArray();
    _jsp_string33 = "&nbsp;&nbsp;|&nbsp;&nbsp;WebApp : ".toCharArray();
    _jsp_string46 = "\">Login</a></td>\r\n<td class=\"dropdown\">\r\n  <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\"><i class=\"fa fa-gear fa-lg text-primary\"></i>&nbsp;<span class=\"caret\"></span></a>\r\n  <ul class=\"dropdown-menu\">\r\n    <li><a href=\"params/tableparam.jsp?JNDIDSN=".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string17 = "\" target=\"_blank\"> SQL Script</a> to create database  structure  ( MySQL )</li>\r\n".toCharArray();
    _jsp_string2 = "\r\n\r\n".toCharArray();
    _jsp_string25 = "\" target=\"_blank\">Tables</a></td>\r\n		<td><a href=\"".toCharArray();
    _jsp_string60 = " </p>\r\n".toCharArray();
  }
}
