/*
 * JSP generated by Resin-4.0.47 (built Thu, 03 Dec 2015 10:34:34 PST)
 */

package _jsp._user._forms;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import com.beanwiz.*;
import java.util.*;
import java.text.*;
import java.lang.*;
import java.sql.*;
import javax.servlet.*;
import javax.servlet.http.*;
import javax.naming.*;
import javax.sql.*;
import com.webapp.utils.*;

public class _formvalidate__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    java.util.TreeMap ManFieldMap;
    synchronized (pageContext.getSession()) {
      ManFieldMap = (java.util.TreeMap) pageContext.getSession().getAttribute("ManFieldMap");
      if (ManFieldMap == null) {
        ManFieldMap = new java.util.TreeMap();
        pageContext.getSession().setAttribute("ManFieldMap", ManFieldMap);
      }
    }
    out.write(_jsp_string1, 0, _jsp_string1.length);
    java.util.Vector ManField;
    synchronized (pageContext.getSession()) {
      ManField = (java.util.Vector) pageContext.getSession().getAttribute("ManField");
      if (ManField == null) {
        ManField = new java.util.Vector();
        pageContext.getSession().setAttribute("ManField", ManField);
      }
    }
    out.write(_jsp_string1, 0, _jsp_string1.length);
     
response.setDateHeader("Expires", 0 );
response.setHeader("Cache-Control", "no-cache, post-check=0, pre-check=0"); 
response.setHeader("Pragma", "no-cache"); 

String appPath = request.getContextPath() ;
String thisFile = appPath+request.getServletPath() ;

com.beanwiz.LoggedUser LogUsr  = (com.beanwiz.LoggedUser)session.getAttribute("theWizardUser");
if(LogUsr == null ) LogUsr =  LoginHelper.autoLoginCheck(application,session,request );

String JNDIDSN = request.getParameter("JNDIDSN");
String TableName = request.getParameter("TableName");


    out.write(_jsp_string2, 0, _jsp_string2.length);
    pageContext.include("/assets/include-page/common/meta-tag.jsp", true);out.write(_jsp_string3, 0, _jsp_string3.length);
    pageContext.include("/assets/include-page/css/main-css.jsp", true);out.write(_jsp_string4, 0, _jsp_string4.length);
    pageContext.include("/assets/include-page/common/main-head-js.jsp", true);out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print((appPath ));
    out.write(_jsp_string6, 0, _jsp_string6.length);
    out.print((appPath ));
    out.write(_jsp_string7, 0, _jsp_string7.length);
    out.print((appPath ));
    out.write(_jsp_string8, 0, _jsp_string8.length);
    out.print((appPath ));
    out.write(_jsp_string9, 0, _jsp_string9.length);
     
Context env = (Context) new InitialContext().lookup("java:comp/env");
DataSource source = (DataSource) env.lookup(JNDIDSN);
Connection conn = source.getConnection();
String query = BeanwizHelper.openTableSQL(conn, TableName);

try 
{
java.sql.Statement stmt = conn.createStatement();
java.sql.ResultSet rslt = stmt.executeQuery(query);
java.sql.ResultSetMetaData rsmd = rslt.getMetaData();
int count  = rsmd.getColumnCount() ;

if("POST".equalsIgnoreCase(request.getMethod()))
{ 
// Process submitted form

    out.write(_jsp_string10, 0, _jsp_string10.length);
    
for(int n = 1 ; n <= count ; n++ )
{	
	String ColName = rsmd.getColumnName(n) ;	
	if( request.getParameter("CHECK_"+ColName)!=null ) if(!ManField.contains(ColName)) ManField.add(ColName);
	String[] InputType = request.getParameterValues(ColName);
			 int j1 =0;
			 StringBuilder sb1 = new StringBuilder();
			 for(String s1:InputType)
       {
			   if(j1>0)sb1.append(",");
				 sb1.append(s1); 
			   j1++;
			 }
	ManFieldMap.put(ColName, sb1) ;		 	
		

    out.write(_jsp_string11, 0, _jsp_string11.length);
    out.print((n ));
    out.write(_jsp_string12, 0, _jsp_string12.length);
    out.print((ColName ));
    out.write(_jsp_string12, 0, _jsp_string12.length);
    out.print((ManFieldMap.get(ColName)));
    out.write(_jsp_string12, 0, _jsp_string12.length);
    if(ManField.contains(ColName)){
    out.write(_jsp_string13, 0, _jsp_string13.length);
    }else{
    out.write(_jsp_string14, 0, _jsp_string14.length);
    }
    out.write(_jsp_string15, 0, _jsp_string15.length);
    
} // end for

    out.write(_jsp_string16, 0, _jsp_string16.length);
    	 
}
else
{
// show form
ManField.clear();
ManFieldMap.clear();

    out.write(_jsp_string17, 0, _jsp_string17.length);
    out.print((thisFile ));
    out.write(_jsp_string18, 0, _jsp_string18.length);
    out.print((JNDIDSN ));
    out.write(_jsp_string19, 0, _jsp_string19.length);
    out.print((TableName ));
    out.write(_jsp_string20, 0, _jsp_string20.length);
    
for(int n = 1 ; n <= count ; n++ )
{	
	 String ColName = rsmd.getColumnName(n) ;
	 String ColType = rsmd.getColumnTypeName(n);

    out.write(_jsp_string21, 0, _jsp_string21.length);
    out.print((ColName ));
    out.write(_jsp_string22, 0, _jsp_string22.length);
    out.print((ColName ));
    out.write(_jsp_string23, 0, _jsp_string23.length);
     if(ManField.contains(ColName))  out.print("checked=\"checked\"") ; 
    out.write(_jsp_string24, 0, _jsp_string24.length);
    out.print((ColName ));
    out.write(_jsp_string25, 0, _jsp_string25.length);
    out.print((n ));
    out.write(_jsp_string26, 0, _jsp_string26.length);
    out.print((ColName ));
     if( rsmd.isAutoIncrement(n)) { 
    out.write(_jsp_string27, 0, _jsp_string27.length);
     } 
    out.write(_jsp_string12, 0, _jsp_string12.length);
    out.print((ColType ));
    out.write(_jsp_string12, 0, _jsp_string12.length);
    out.print((ValidationType.getDropList(ColName, ColName, (short)1, false, false, "form-control selectpicker show-tick", "data-container='body' data-live-search='false' multiple data-selected-text-format='count > 1' data-actions-box='true'") ));
    out.write(_jsp_string28, 0, _jsp_string28.length);
    	  
}// end for(int n = 1 ; n <= count ; n++ ) 

    out.write(_jsp_string29, 0, _jsp_string29.length);
     
} // end of if("POST".equalsIgnoreCase(request.getMethod()))
rslt.close();
stmt.close();
}		 
finally
{
conn.close();
} 

    out.write(_jsp_string30, 0, _jsp_string30.length);
    pageContext.include("/assets/include-page/js/main-js.jsp", true);out.write(_jsp_string31, 0, _jsp_string31.length);
    pageContext.include("/assets/include-page/js/iframe-resizer/iframeResizer-contentWindow-js.jsp", true);out.write(_jsp_string32, 0, _jsp_string32.length);
    out.print((ManFieldMap.size() ));
    out.write(_jsp_string33, 0, _jsp_string33.length);
    out.print((ManField.size() ));
    out.write(_jsp_string34, 0, _jsp_string34.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 8324212715306645294L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("user/forms/formvalidate.jsp"), -5680056676032559271L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string26;
  private final static char []_jsp_string20;
  private final static char []_jsp_string24;
  private final static char []_jsp_string10;
  private final static char []_jsp_string27;
  private final static char []_jsp_string28;
  private final static char []_jsp_string17;
  private final static char []_jsp_string9;
  private final static char []_jsp_string23;
  private final static char []_jsp_string2;
  private final static char []_jsp_string21;
  private final static char []_jsp_string25;
  private final static char []_jsp_string6;
  private final static char []_jsp_string12;
  private final static char []_jsp_string31;
  private final static char []_jsp_string7;
  private final static char []_jsp_string4;
  private final static char []_jsp_string13;
  private final static char []_jsp_string19;
  private final static char []_jsp_string0;
  private final static char []_jsp_string16;
  private final static char []_jsp_string32;
  private final static char []_jsp_string29;
  private final static char []_jsp_string22;
  private final static char []_jsp_string3;
  private final static char []_jsp_string34;
  private final static char []_jsp_string33;
  private final static char []_jsp_string5;
  private final static char []_jsp_string30;
  private final static char []_jsp_string15;
  private final static char []_jsp_string1;
  private final static char []_jsp_string18;
  private final static char []_jsp_string8;
  private final static char []_jsp_string11;
  private final static char []_jsp_string14;
  static {
    _jsp_string26 = "</label>\r\n</span>\r\n</td>\r\n<td>".toCharArray();
    _jsp_string20 = "\" />\r\n\r\n<div class=\"panel panel-default\">\r\n<!-- Default panel contents -->\r\n<div class=\"panel-heading\"><i class=\"fa fa-tasks fa-lg text-primary\"></i>&nbsp;&nbsp;Fields : Form Label</div>\r\n<div class=\"panel-body\"><span class=\"pull-right\"><button type=\"submit\" class=\"btn btn-primary\">Submit</button></span></div>\r\n\r\n<!-- Table -->\r\n<div class=\"table-responsive\">\r\n<table class=\"table table-striped table-bordered table-condensed\" id=\"Form_validation\">\r\n<thead>\r\n<tr>\r\n<th>\r\n<span class=\"checkbox checkbox-inline checkbox-primary\">\r\n    <input type=\"checkbox\" name=\"checkall\" id=\"checkall\" >\r\n    <label for=\"checkall\"><b>Mandatory ?</b></label>\r\n</span>\r\n</th>\r\n<th>Column</th>\r\n<th>Type</th>\r\n<th width=\"30%\">Validation Type</th>\r\n</tr>\r\n</thead>\r\n<tbody>\r\n".toCharArray();
    _jsp_string24 = " >\r\n    <label for=\"CHECK_".toCharArray();
    _jsp_string10 = "\r\n<ul class=\"list-group\">\r\n  <li class=\"list-group-item list-group-item-success\">Input Items in Tree Map: <span id=\"trmap\"></span></li>\r\n	<li class=\"list-group-item list-group-item-success\">Mandatory Fileds: <span id=\"vlmap\"></span></li>\r\n</ul>\r\n\r\n<br />\r\n\r\n<div class=\"table-responsive\">\r\n<table class=\"table table-striped table-bordered table-condensed\">\r\n<thead>\r\n<tr>\r\n<th>#</th>\r\n<th>Column</th>\r\n<th>Type</th>\r\n<th>Mandatory</th>\r\n</tr>\r\n</thead>\r\n<tbody>\r\n".toCharArray();
    _jsp_string27 = "&nbsp;&nbsp;<span class=\"label label-default\">A</span>".toCharArray();
    _jsp_string28 = "</td>\r\n</tr>\r\n".toCharArray();
    _jsp_string17 = "\r\n<form action=\"".toCharArray();
    _jsp_string9 = "/assets/vendor/shjs-highlight-code/', '.min.js');		\r\n		var stop=new Date();\r\n		document.getElementById('processTime').appendChild(document.createTextNode('Time taken to complete process: '+(stop-start)+' ms'));\r\n	}\r\n  </script>\r\n\r\n<style type=\"text/css\">\r\n.clickablePanel{cursor: pointer;}\r\n.clickablePanel .glyphicon{background: rgba(0, 0, 0, 0.15);display: inline-block;padding: 6px 12px;border-radius: 4px}\r\n.clickablePanel  span{margin-top: -23px;font-size: 15px;margin-right: -9px;}\r\n</style>\r\n</head>\r\n<body onload=\"init();\" style=\"margin-bottom: 0px;padding-top: 10px;\">   \r\n<div class=\"container-fluid\">\r\n\r\n      <div class=\"panel panel-default\">\r\n        <div class=\"panel-heading clickablePanel\">\r\n          <h4 class=\"panel-title\">\r\n					<i class=\"fa fa-database text-primary\"></i>&nbsp;&nbsp;Sample Code for regexp</span>\r\n					</h4>\r\n					<span class=\"pull-right p1\"><i class=\"glyphicon glyphicon-minus\"></i></span>\r\n        </div>\r\n        <div class=\"panel-body\">\r\n					<div id=\"processTime\" class=\"well well-sm\"></div>\r\n          <pre class=\"sh_javascript\" title=\"sample code\">\r\nregexp: {\r\n    regexp: /^[a-zA-Z]+$/,\r\n    message: 'The name can only consist of alphabetical'\r\n}\r\n\r\nregexp: {\r\n    regexp: /^[a-zA-Z0-9_]+$/,\r\n    message: 'The name can only consist of alphabetical, number and underscore'\r\n}\r\n\r\nregexp: {\r\n    regexp: /^[a-zA-Z\\s]+$/,\r\n    message: 'The name can only consist of alphabetical and space'\r\n}\r\n\r\nregexp: {\r\n    regexp: /^[a-zA-Z0-9_\\.]+$/,\r\n    message: 'The name can only consist of alphabetical, number, dot and underscore'\r\n}\r\n          </pre>\r\n\r\n        </div>\r\n      </div>			\r\n\r\n\r\n".toCharArray();
    _jsp_string23 = "\" ".toCharArray();
    _jsp_string2 = "\r\n<!DOCTYPE HTML>\r\n<!--[if lt IE 7]>      <html class=\"no-js lt-ie9 lt-ie8 lt-ie7\" lang=\"en\"> <![endif]-->\r\n<!--[if IE 7]>         <html class=\"no-js lt-ie9 lt-ie8\" lang=\"en\"> <![endif]-->\r\n<!--[if IE 8]>         <html class=\"no-js lt-ie9\" lang=\"en\"> <![endif]-->\r\n<!--[if gt IE 8]><!--> <html class=\"no-js\" lang=\"en\"> <!--<![endif]-->\r\n<head>\r\n".toCharArray();
    _jsp_string21 = "\r\n<tr>\r\n<td>\r\n<span class=\"checkbox checkbox-inline checkbox-primary\">\r\n    <input type=\"checkbox\" name=\"CHECK_".toCharArray();
    _jsp_string25 = "\">".toCharArray();
    _jsp_string6 = "/assets/vendor/shjs-highlight-code/shx_main.min.css\" />\r\n  <!-- Theme file. There are many more themes in the css folder -->\r\n  <link rel=\"stylesheet\" href=\"".toCharArray();
    _jsp_string12 = "</td>\r\n<td>".toCharArray();
    _jsp_string31 = "\r\n<!-- iframeResizer.contentWindow.min.js to be loaded into the target frame -->\r\n".toCharArray();
    _jsp_string7 = "/assets/vendor/shjs-highlight-code/css/sh_acid.min.css\" />\r\n  <!-- Main JS file -->\r\n  <script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string4 = "		\r\n".toCharArray();
    _jsp_string13 = "yes".toCharArray();
    _jsp_string19 = "\" />\r\n<input type=\"hidden\" name=\"TableName\" value=\"".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string16 = "\r\n</tbody>\r\n</table>\r\n</div>		 \r\n\r\n".toCharArray();
    _jsp_string32 = "\r\n<script>\r\n\r\n$(document).on('click', '.panel div.clickablePanel', function (e) {\r\n    var $this = $(this);\r\n    if (!$this.hasClass('panel-collapsed')) {\r\n        $this.parents('.panel').find('.panel-body').slideUp();\r\n        $this.addClass('panel-collapsed');\r\n        $this.find('.p1 i').removeClass('glyphicon-minus').addClass('glyphicon-plus');\r\n    } else {\r\n        $this.parents('.panel').find('.panel-body').slideDown();\r\n        $this.removeClass('panel-collapsed');\r\n        $this.find('.p1 i').removeClass('glyphicon-plus').addClass('glyphicon-minus');\r\n    }\r\n});\r\n\r\n$(\"#Form_validation #checkall\").click(function () {\r\n        if ($(\"#Form_validation #checkall\").is(':checked')) {\r\n            $(\"#Form_validation input[type=checkbox]\").each(function () {\r\n                $(this).prop(\"checked\", true);\r\n            });\r\n\r\n        } else {\r\n            $(\"#Form_validation input[type=checkbox]\").each(function () {\r\n                $(this).prop(\"checked\", false);\r\n            });\r\n        }\r\n    });\r\n		\r\n$(document).ready(function() {\r\n	$(\"#trmap\").html(\"".toCharArray();
    _jsp_string29 = "\r\n</tbody>\r\n</table>\r\n</div>\r\n</div>\r\n</form>\r\n".toCharArray();
    _jsp_string22 = "\" id=\"CHECK_".toCharArray();
    _jsp_string3 = "	\r\n<title>For Form validation</title>	\r\n".toCharArray();
    _jsp_string34 = "\");\r\n	\r\n	$('.panel div.clickablePanel').click();\r\n});		\r\n\r\n</script>\r\n\r\n</body>\r\n</html>\r\n".toCharArray();
    _jsp_string33 = "\");\r\n	$('#vlmap').html(\"".toCharArray();
    _jsp_string5 = "\r\n\r\n  <!-- The follwing are the files that must be added for using SHJS-Extended -->\r\n  <!-- Common Styles -->\r\n  <link rel=\"stylesheet\" href=\"".toCharArray();
    _jsp_string30 = "\r\n\r\n\r\n</div> <!-- /container -->\r\n".toCharArray();
    _jsp_string15 = "</td>			\r\n</tr>\r\n".toCharArray();
    _jsp_string1 = "\r\n".toCharArray();
    _jsp_string18 = "\" method=\"post\">\r\n<input type=\"hidden\" name=\"JNDIDSN\" value=\"".toCharArray();
    _jsp_string8 = "/assets/vendor/shjs-highlight-code/sh_main.js\"></script>\r\n	\r\n  <script type=\"text/javascript\">\r\n	function init() { //body onload\r\n		var start=new Date();\r\n		sh_highlightDocument('".toCharArray();
    _jsp_string11 = "\r\n<tr>     \r\n<td>".toCharArray();
    _jsp_string14 = "No".toCharArray();
  }
}
