/*
 * JSP generated by Resin-4.0.47 (built Thu, 03 Dec 2015 10:34:34 PST)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import com.beanwiz.*;
import java.net.InetAddress;

public class _header__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html");

    out.write(_jsp_string0, 0, _jsp_string0.length);
     
String appPath = request.getContextPath() ;
InetAddress iAddress = InetAddress.getLocalHost();
  String currentIp = iAddress.getHostAddress();
	//InetAddress.getLocalHost().getHostAddress()
	String hostname = iAddress.getHostName();
/*
  InetAddress inet = InetAddress.getLocalHost();
  InetAddress[] ips = InetAddress.getAllByName(inet.getCanonicalHostName());
  if (ips  != null ) {
    for (int i = 0; i < ips.length; i++) {
      out.println(ips[i]+"</br>");
    }
  }
*/

    out.write(_jsp_string1, 0, _jsp_string1.length);
    out.print((appPath ));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((request.getRemoteHost() ));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((hostname ));
    out.write(_jsp_string4, 0, _jsp_string4.length);
    out.print((request.getRemoteAddr() ));
    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print((currentIp ));
    out.write(_jsp_string6, 0, _jsp_string6.length);
    out.print((request.getLocalAddr() ));
    out.write(_jsp_string7, 0, _jsp_string7.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 8324212715306645294L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("header.jsp"), 5331905718568139648L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string6;
  private final static char []_jsp_string4;
  private final static char []_jsp_string3;
  private final static char []_jsp_string2;
  private final static char []_jsp_string0;
  private final static char []_jsp_string5;
  private final static char []_jsp_string1;
  private final static char []_jsp_string7;
  static {
    _jsp_string6 = "</samp></a></li>\r\n						<li><a href=\"#\"><samp><i class=\"fa fa-hand-o-right fa-lg text-primary\"></i>&nbsp;returns the IP of the server the application is running on : ".toCharArray();
    _jsp_string4 = "</samp></a></li>\r\n            <li><a href=\"#\"><samp><i class=\"fa fa-hand-o-right fa-lg text-primary\"></i>&nbsp;returns the clients IP : ".toCharArray();
    _jsp_string3 = "</samp></a></li>\r\n						<li><a href=\"#\"><samp><i class=\"fa fa-hand-o-right fa-lg text-primary\"></i>&nbsp;get Hostname of the current Server name : ".toCharArray();
    _jsp_string2 = "/index.jsp\"><i class=\"fa fa-motorcycle fa-lg text-primary\"></i>&nbsp;&nbsp;Development Tool</a>\r\n        </div>\r\n    <div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n      <ul class=\"nav navbar-nav\">\r\n        <li class=\"dropdown\"> \r\n				  <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\"><i class=\"fa fa-umbrella fa-lg text-primary\"></i>&nbsp;&nbsp;User Host&nbsp;<span class=\"caret\"></span></a>\r\n          <ul class=\"dropdown-menu\">\r\n						<li><a href=\"#\"><samp><i class=\"fa fa-hand-o-right fa-lg text-primary\"></i>&nbsp;Automatic login permitted for Host [localhost]</samp></a></li>\r\n            <li><a href=\"#\"><samp><i class=\"fa fa-hand-o-right fa-lg text-primary\"></i>&nbsp;Host : ".toCharArray();
    _jsp_string0 = "\r\n".toCharArray();
    _jsp_string5 = "</samp></a></li>\r\n						<li><a href=\"#\"><samp><i class=\"fa fa-hand-o-right fa-lg text-primary\"></i>&nbsp;Host Addr [get the local address] : ".toCharArray();
    _jsp_string1 = "\r\n\r\n<nav class=\"navbar navbar-default navbar-fixed-top site-header\">\r\n  <div class=\"container-fluid\">\r\n        <div class=\"navbar-header\">\r\n          <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\">\r\n            <span class=\"sr-only\">Toggle navigation</span>\r\n            <span class=\"icon-bar\"></span>\r\n            <span class=\"icon-bar\"></span>\r\n            <span class=\"icon-bar\"></span>\r\n          </button>\r\n          <a class=\"navbar-brand\" href=\"".toCharArray();
    _jsp_string7 = "</samp></a></li>\r\n          </ul>\r\n        </li>\r\n      </ul>\r\n      <ul class=\"nav navbar-nav navbar-right\">\r\n        <li><a href=\"#contact\" data-toggle=\"modal\" data-target=\"#myModal\"><i class=\"fa fa-ambulance fa-lg text-primary\"></i>&nbsp;&nbsp;Contact</a></li>\r\n      </ul>\r\n    </div>\r\n    <!--/.nav-collapse -->\r\n  </div>\r\n</nav>\r\n\r\n<!-- Modal -->\r\n<div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\"><!--  animated zoomInDown -->\r\n  <div class=\"modal-dialog\" role=\"document\">\r\n    <div class=\"modal-content\">\r\n      <div class=\"modal-header\">\r\n        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\r\n        <h4 class=\"modal-title\" id=\"myModalLabel\"><i aria-hidden=\"true\" class=\"icon glyphicon glyphicon-phone-alt\"></i>&nbsp;&nbsp;Contact</h4>\r\n      </div>\r\n      <div class=\"modal-body\">\r\n        Na male\r\n      </div>\r\n      <div class=\"modal-footer\">\r\n        <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n      </div>\r\n    </div>\r\n  </div>\r\n</div>\r\n".toCharArray();
  }
}
