/*
 * JSP generated by Resin-4.0.47 (built Thu, 03 Dec 2015 10:34:34 PST)
 */

package _jsp._user._jsp._include_22dpage;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import javax.servlet.*;
import javax.servlet.http.*;
import javax.naming.*;
import javax.sql.*;
import com.beanwiz.TableColumn;

public class _show_22drecord_22dpage__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html");

    java.util.TreeMap FieldMap;
    synchronized (pageContext.getSession()) {
      FieldMap = (java.util.TreeMap) pageContext.getSession().getAttribute("FieldMap");
      if (FieldMap == null) {
        FieldMap = new java.util.TreeMap();
        pageContext.getSession().setAttribute("FieldMap", FieldMap);
      }
    }
    java.util.Vector ManField;
    synchronized (pageContext.getSession()) {
      ManField = (java.util.Vector) pageContext.getSession().getAttribute("ManField");
      if (ManField == null) {
        ManField = new java.util.Vector();
        pageContext.getSession().setAttribute("ManField", ManField);
      }
    }
    

String BeanName = request.getParameter("BeanName");
String IDField = request.getParameter("IDField");
String EntityName = request.getParameter("EntityName");
if(EntityName ==null)  EntityName = "?" ;

java.sql.ResultSetMetaData rsmd = (java.sql.ResultSetMetaData)request.getAttribute("RSMD");
int count  = rsmd.getColumnCount();

    out.write(_jsp_string0, 0, _jsp_string0.length);
    out.print((BeanName  ));
    out.write('.');
    out.print((IDField  ));
    out.write(_jsp_string1, 0, _jsp_string1.length);
    out.print((IDField  ));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((BeanName  ));
    out.write('.');
    out.print((IDField  ));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((IDField  ));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((BeanName  ));
    out.write('.');
    out.print((IDField  ));
    out.write(_jsp_string4, 0, _jsp_string4.length);
    
    out.print("\r\n");
    int n=0;
    for (n=1 ;  n<=count; n++)
    { 
    String ColName = rsmd.getColumnName(n) ;
    String ColVarName= BeanName+"."+ColName.replace((char)32, '_' ) ;
    int ColType = rsmd.getColumnType(n);
     
    
    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print("<"+"%=FieldLabel["+BeanName+"_"+ColName+"] %"+">" ) ;
    out.write(_jsp_string6, 0, _jsp_string6.length);
    
    switch(ColType)
    {
      case java.sql.Types.DATE:
    	 
    out.write(_jsp_string7, 0, _jsp_string7.length);
    out.print((ColVarName ));
    out.write(_jsp_string8, 0, _jsp_string8.length);
     
    	break;
    	case java.sql.Types.TIMESTAMP:
    	 
    out.write(_jsp_string9, 0, _jsp_string9.length);
    out.print((ColVarName ));
    out.write(_jsp_string8, 0, _jsp_string8.length);
    
    	break;
    	case java.sql.Types.TIME:
    	 
    out.write(_jsp_string10, 0, _jsp_string10.length);
    out.print((ColVarName ));
    out.write(_jsp_string11, 0, _jsp_string11.length);
    
    	break;
    	case java.sql.Types.LONGVARBINARY:
    	case java.sql.Types.VARBINARY:
    	case java.sql.Types.BINARY:
    	case java.sql.Types.BLOB:
    	 
    out.write(_jsp_string12, 0, _jsp_string12.length);
    
    	break;
    	default: 
    out.write(_jsp_string13, 0, _jsp_string13.length);
    out.print((ColVarName ));
    out.write(_jsp_string8, 0, _jsp_string8.length);
    
    }// end switch case
    out.print("\r\n");
    if(n%1==0)out.print("    </tr>\r\n");
		if(n%1==0 && n!=count)out.print("    <tr>\r\n");		
    } // end for
    if(n%1==0)out.print(""); 
    
    out.write(_jsp_string14, 0, _jsp_string14.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 8324212715306645294L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("user/jsp/include-page/show-record-page.jsp"), -9005829037593612232L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string13;
  private final static char []_jsp_string14;
  private final static char []_jsp_string9;
  private final static char []_jsp_string5;
  private final static char []_jsp_string4;
  private final static char []_jsp_string2;
  private final static char []_jsp_string1;
  private final static char []_jsp_string7;
  private final static char []_jsp_string3;
  private final static char []_jsp_string11;
  private final static char []_jsp_string6;
  private final static char []_jsp_string8;
  private final static char []_jsp_string0;
  private final static char []_jsp_string10;
  private final static char []_jsp_string12;
  static {
    _jsp_string13 = "   <td><%=StrValue(".toCharArray();
    _jsp_string14 = "    </table>\r\n    </div>\r\n  </div>\r\n</div>\r\n<!-- End Showing Single Record Data  -->".toCharArray();
    _jsp_string9 = "   <td><%=DateTimeHelper.showDateTimePicker(".toCharArray();
    _jsp_string5 = "       <td><span class=\"blue-grey-700\">".toCharArray();
    _jsp_string4 = " %>\">Menu Link 2</a>\r\n      </li>\r\n    </ul>		\r\n    </div>		\r\n    -->\r\n  </div>\r\n  <div class=\"col-sm-9\">\r\n    <div class=\"table-responsive\">\r\n    <table class=\"table table-bordered table-condensed table-striped\">\r\n    <tr>".toCharArray();
    _jsp_string2 = "=<%=".toCharArray();
    _jsp_string1 = " %></h4>\r\n    <!--  uncomment this \r\n    <div class=\"well well-sm\">\r\n    <ul class=\"list-group list-group-gap\" style=\"margin-bottom: 0px;\">\r\n      <li class=\"list-group-item\">\r\n        <i aria-hidden=\"true\" class=\"icon fa fa-anchor iccolor\"></i><a href=\"#?".toCharArray();
    _jsp_string7 = "   <td><%=DateTimeHelper.showDatePicker(".toCharArray();
    _jsp_string3 = " %>\">Menu Link 1</a>\r\n      </li>\r\n      <li class=\"list-group-item\">\r\n        <i aria-hidden=\"true\" class=\"icon fa fa-anchor iccolor\"></i><a href=\"#?".toCharArray();
    _jsp_string11 = ", \"Show\") %></td>".toCharArray();
    _jsp_string6 = "</span></td>\r\n    ".toCharArray();
    _jsp_string8 = ") %></td>".toCharArray();
    _jsp_string0 = "<!-- Start Showing Single Record Data  -->\r\n<div class=\"row\">\r\n  <div class=\"col-sm-3\">\r\n    <h4>ID : <%=".toCharArray();
    _jsp_string10 = "   <td><%=DateTimeHelper.showTimeClockPicker(".toCharArray();
    _jsp_string12 = "   <td>Binary Data</td><!-- /include-page/js/bootstrap-filestyle-js.jsp -->".toCharArray();
  }
}
